### ISSUE TITLE
validation fails without primer sheet

### ISSUE THREAD

**Issue by atgerritsen** [msettles/dbcAmplicons#15]
even if there are no primer sequences in the samples and no primers identified in the sample sheet, validation requires a primer sheet. a dummy sheet will pass validation.

**Comment by atgerritsen** [comment]
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/dbcAmplicons/preprocess_app.py", line 50, in start
    if v.validateSample(bcTable, prTable, sTable, debug) != 0:
UnboundLocalError: local variable 'prTable' referenced before assignment

**Comment by msettles** [comment]
Fixed, validate fails if sample sheet contains primers but no primer sheet is specified, does not fail is sample sheet has no primers and no primer is identified.
