### ISSUE TITLE
Format of read ID differs from manual when using "--keepPrimers"

### ISSUE THREAD

**Issue by samhunter** [msettles/dbcAmplicons#27]
The default output of **dbcAmplicons preprocess** is documented in the DBC_ampliconsUserManual as being formatted like:

{Sequence ID (Illumina header) } : {SampleID} : {PrimerPairID} {Barcode1|#differences1|Barcode2|#differences2} {PrimerForward|#differences|bpTrimmed}

However, this format is only used when "--keepPrimers" is not passed to **preprocess**.

Example without "--keepPrimers" (format described in the manual):
@M01380:62:000000000-B547W:1:1102:20354:1000 1:N:0:AG_5856:ITS3_ITS4 NTATCGCT|1|NTCTCTAT|1 ITS3_CS1|1|20|

Example with "--keepPrimers" (differs from what is described in the manual):
@M01380:62:000000000-B547W:1:1102:12519:1279 1:N:0:AG_1105 ACGAATTC|0|CAGGACGT|0

This might be intended behavior. I couldn't find documentation for it in the manual however, and it resulted in some issues with a downstream pipeline. Additionally, because no information is reported regarding the target specific primer (number of differences, which primer was identified, bpTrimmed) it isn't clear whether dbcAmplicons is still looking for the primer within the read.

I think the preferred behavior would be to report the primer, num mismatches, as well as 0bp trimmed?

**Comment by msettles** [comment]
left primer details in read header
