### ISSUE TITLE
convert2ReadTo4Read.py barcode error

### ISSUE THREAD

**Issue by rajewski** [msettles/dbcAmplicons#39]
Using the following call:
`dbcAmplicons/scripts/python/convert2ReadTo4Read.py -1 data/003237_H-2D_S30_R1_filtered.fastq.gz -2 data/003237_H-2D_S30_R2_filtered.fastq.gz --debug` 

I get the error:
`ERROR:[TwoSequenceReadSet] Unknown error occured generating four read set`
`Cleaning up.`
`A fatal error was encountered.`
`Traceback (most recent call last):`
`  File "dbcAmplicons/scripts/python/convert2ReadTo4Read.py", line 48, in start`
`   self.run_out.addRead(read.getFourReads(bc1_length=barcode1, bc2_length=barcode2))`
`  File "build/bdist.linux-x86_64/egg/dbcAmplicons/sequenceReads.py", line 355, in getFourReads`
`    raise Exception("string in the barcode is not %s characters" % str(bc1_length + bc2_length))`
`Exception: string in the barcode is not 16 characters`

When I try to add in the `-p` or `-q` flags the error remains the same.

**Comment by pmhenry** [comment]
It looks like you did not specify a barcode file which you will need to do to run this script. If your barcodes are different lengths than the default then you will need to specify their lengths with the -p or -q flags. 

The latest version of dbcAmplicons has an '--inline' option in the preprocess app that enables compatibility with two-read datasets. This may be a better option for you if you are converting 2 to 4 reads for downstream compatibility with the rest of dbcAmplicons.

Let me know if this doesn't solve your issue

**Comment by rajewski** [comment]
I think this would fix the issue if I were starting with 'rawer' data. To run the preprocess app, I would need to provide a primer and barcode file.

The library construction, etc were done by my core facility. They have provided me with fastq files with the primers, adaptors, barcode, and low quality bases removed. I also don't know explicitly the primers, etc that they used. Is there a way to enter into the workflow with this sort of data?
