### ISSUE TITLE
classify app should include rdp classifier 

### ISSUE THREAD

**Issue by atgerritsen** [msettles/dbcAmplicons#7]
using external path to RDP classifier but creates problems if user is not familiar with the path to RDP. When including the classifer.jar file within the dbcAmplicons app, determine if the classifier can be packed and made within it.

**Comment by msettles** [comment]
new uses an environment variable to set the RDP classifier path, so set an environment variable RDP_PATH and the classify app will use it. No need any more to set the parameter rdpPath
